import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, KFold, GroupKFold
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score

# 1. Set up the dashboard interface
st.set_page_config(page_title="Flood Simulator", layout="wide")
st.title("🌊 Flood Susceptibility Simulator (Baseline Model)")
st.write("This dashboard replicates the Mangkhaseum et al. (2024) Random Forest baseline.")

# 2. Load the data generated by data_prep.py
@st.cache_data
def load_data():
    return pd.read_csv('data/baseline_training_data.csv')

try:
    df = load_data()
    st.success("✅ Training dataset loaded successfully!")

    # Show a quick preview of the tabular data
    st.write("Data Preview (First 5 Rows):")
    st.dataframe(df.head())

    # 3. Define Features (X) and Target (y)
    # All 11 baseline conditioning factors from Mangkhaseum et al. (2024):
    # Elevation, Slope, Aspect, Curvature, TWI, SPI, DTR (from DEM),
    # NDVI, LULC, Rainfall, Soil_Type
    feature_cols = ['Elevation', 'Slope', 'Aspect', 'Curvature', 'TWI', 'SPI', 'DTR',
                     'Soil_Type', 'NDVI', 'LULC', 'Rainfall']
    X = df[feature_cols]
    y = df['Flood_Class']

    # Split into 70% Training and 30% Testing
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    st.write(f"**Training Data:** {len(X_train)} points | **Testing Data:** {len(X_test)} points")

    # 4. Model Training & Evaluation
    st.subheader("Model Training & Evaluation")

    eval_mode = st.radio(
        "Evaluation method",
        ["Single 70/30 split", "Random 5-fold CV", "Spatially-blocked 5-fold CV (honest estimate)"],
        help=("Spatially-blocked CV groups nearby points together so train/test never share "
              "a neighborhood -- it corrects for spatial autocorrelation inflating accuracy.")
    )

    if st.button("Train Baseline Model"):
        with st.spinner("Training Random Forest in the background..."):

            if eval_mode == "Single 70/30 split":
                rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
                rf_model.fit(X_train, y_train)
                predictions = rf_model.predict(X_test)
                probabilities = rf_model.predict_proba(X_test)[:, 1]
                acc = accuracy_score(y_test, predictions)
                auc = roc_auc_score(y_test, probabilities)
                acc_std, auc_std = None, None

            elif eval_mode == "Random 5-fold CV":
                kf = KFold(n_splits=5, shuffle=True, random_state=42)
                accs, aucs = [], []
                for tr_idx, te_idx in kf.split(X):
                    rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
                    rf_model.fit(X.iloc[tr_idx], y.iloc[tr_idx])
                    pred = rf_model.predict(X.iloc[te_idx])
                    proba = rf_model.predict_proba(X.iloc[te_idx])[:, 1]
                    accs.append(accuracy_score(y.iloc[te_idx], pred))
                    aucs.append(roc_auc_score(y.iloc[te_idx], proba))
                acc, auc = np.mean(accs), np.mean(aucs)
                acc_std, auc_std = np.std(accs), np.std(aucs)

            else:  # Spatially-blocked 5-fold CV
                coords = df[['Latitude', 'Longitude']].values
                km = KMeans(n_clusters=10, random_state=42, n_init=10)
                groups = km.fit_predict(coords)
                gkf = GroupKFold(n_splits=5)
                accs, aucs = [], []
                for tr_idx, te_idx in gkf.split(X, y, groups=groups):
                    rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
                    rf_model.fit(X.iloc[tr_idx], y.iloc[tr_idx])
                    pred = rf_model.predict(X.iloc[te_idx])
                    proba = rf_model.predict_proba(X.iloc[te_idx])[:, 1]
                    accs.append(accuracy_score(y.iloc[te_idx], pred))
                    aucs.append(roc_auc_score(y.iloc[te_idx], proba))
                acc, auc = np.mean(accs), np.mean(aucs)
                acc_std, auc_std = np.std(accs), np.std(aucs)

            # 5. Display the Results on the Dashboard
            st.write("### 📊 Performance Metrics")
            col1, col2 = st.columns(2)
            if acc_std is not None:
                col1.metric("Model Accuracy", f"{acc:.4f}", delta=f"±{acc_std:.4f} across folds", delta_color="off")
                col2.metric("AUROC Score", f"{auc:.4f}", delta=f"±{auc_std:.4f} across folds", delta_color="off")
            else:
                col1.metric("Model Accuracy", f"{acc:.4f}")
                col2.metric("AUROC Score", f"{auc:.4f}")

            if eval_mode == "Spatially-blocked 5-fold CV (honest estimate)":
                st.info(
                    "This score reflects performance on geographically unseen areas -- "
                    "a more realistic estimate of how the model would generalize to a new region "
                    "than a random split, which can be inflated by spatial autocorrelation."
                )

except FileNotFoundError:
    st.error("Could not find data/baseline_training_data.csv. Make sure your data_prep.py script ran successfully!")